---
title: "Geography 13"
author: "[Lauren Whightsil](https://github.com/laurenwhightsil)"
subtitle: 'Lab 03: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---

```{r package-options, warning=FALSE, message=FALSE}
# SPDS
library(tidyverse)
library(sf)
library(units)
# Data
library(USAboundaries)
library(rnaturalearthdata)
#Visualization
library(gghighlight)
library(ggrepel)
library(knitr)
library(kableExtra)
```
# Question 1
```{r, warning=FALSE, message=FALSE}
# 1.1 Define projection
eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'
### This projection maps areas in the range of 20 to 60 degrees of latitude. The standard parallel lies at 40 degrees of latitude and the central meridian is at -96 degrees of longitude. It uses the North American Datum of 1983.

# 1.2 Filter to state boundaries of the contiguous United States
CONUS <- USAboundaries::us_states(resolution = "low") %>% filter(!state_name %in% c("Hawaii", "Puerto Rico", "Alaska", "Guam")) %>% 
  st_transform(eqdc) %>% st_as_sf()

# 1.3 Get country boundaries for Mexico, the USA, and Canada
countrybounds <- rnaturalearthdata::countries110 %>% st_as_sf() %>% filter(admin %in% c("Mexico", "United States of America", "Canada")) %>% st_transform(eqdc)

# 1.4 Get city locations from the CSV file
allcities = read_csv("../data/simplemaps_uscities_basicv1.73/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs= 4269) %>%
  st_transform(eqdc) %>%
  filter(!state_name %in% c("Hawaii", "Puerto Rico", "Alaska", "Guam")) %>% 
  mutate(city_state= paste(city, state_id)) %>% 
  select(!c(city_ascii, density, military, incorporated, timezone, ranking, zips))

```
# Question 2
```{r, warning=FALSE, message=FALSE}
dist_5070_km = function(g1, g2){
  g2 = st_transform(g2, crs= st_crs(g1))
  drop_units(set_units(st_distance(g1,g2),"km")) %>%
  as.vector()
}
countries = st_as_sf(rnaturalearthdata::countries110)

# 2.1 Distance to USA Border
get_conus= function(data, var){
  filter(data, !get(var) %in% c("Hawaii", "Puerto Rico", "Guam", "Alaska", "District of Columbia"))
}

USborders= get_conus(us_states(), "name") %>%
  st_union() %>%
  st_cast("MULTILINESTRING")

q2.1= dist_5070_km(allcities, USborders)
allcities = mutate(allcities, q2.1)

table2.1 <- allcities %>% 
  slice_max(q2.1, n=5) %>% 
  select(city, state_name, q2.1) %>% st_set_geometry(NULL)

t2.1= knitr::kable(table2.1, caption= "Cities Farthest from a USA Border", col.names= c("City Name", "State", "Distance (km)")) %>%
   kable_styling("striped", full_width = TRUE, font_size = 14)
t2.1

# 2.2 Distance to States (km)
stateborders = get_conus(us_states(), "name") %>%
  st_combine() %>%
  st_cast("MULTILINESTRING")

q2.2= dist_5070_km(allcities, stateborders)
allcities = mutate(allcities, q2.2)

table2.2 <- allcities %>% 
  slice_max(q2.2, n=5) %>% 
  select(city, state_name, q2.2) %>% st_set_geometry(NULL)

t2.2= knitr::kable(table2.2, caption= "Cities Farthest from a State Border", col.names= c("City Name", "State", "Distance (km)")) %>%
   kable_styling("striped", full_width = TRUE, font_size = 14)
t2.2

# 2.3 Distance to Mexico (km)
Mexico= countries%>% filter(sovereignt== "Mexico")

q2.3= dist_5070_km(allcities, Mexico)
allcities = mutate(allcities, q2.3)

table2.3 <- allcities %>% 
  slice_max(q2.3, n=5) %>% 
  select(city, state_name, q2.3) %>% st_set_geometry(NULL)

t2.3= knitr::kable(table2.3, caption= "Cities Farthest from the Mexican Border", col.names= c("City Name", "State", "Distance (km)")) %>%
   kable_styling("striped", full_width = TRUE, font_size = 14)
t2.3

# 2.4 Distance to Canada (km)
Canada= countries%>% filter(sovereignt== "Canada")

q2.4= dist_5070_km(allcities, Canada)
allcities = mutate(allcities, q2.4)

table2.4 <- allcities %>% 
  slice_max(q2.4, n=5) %>% 
  select(city, state_name, q2.4) %>% st_set_geometry(NULL)

t2.4= knitr::kable(table2.4, caption= "Cities Farthest from the Canadian Border", col.names= c("City Name", "State", "Distance (km)")) %>%
   kable_styling("striped", full_width = TRUE, font_size = 14)
t2.4
```
# Question 3
```{r, warning=FALSE, message=FALSE}
# 3.1 Data
largest10 <- allcities %>% 
  slice_max(population, n=10) %>% 
  select(city, state_id, population)

q3.1 = ggplot() +
  geom_sf(data = Mexico, fill= "seagreen4") +
  geom_sf(data = Canada, fill= "tomato3") +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = stateborders, col= "royalblue1", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  geom_sf(data = largest10, col= "gray15") +
  ggrepel::geom_label_repel(data= largest10, 
                            aes(label= city, geometry= geometry), 
                            stat= "sf_coordinates", size= 2) +
  labs(title= "Ten Most Populous US Cities", x= 'longitude', y='latitude')

q3.1

# 3.2 City Distance from the Border
cities3.2 <- allcities %>% 
  slice_max(q2.1, n=5) %>% 
  select(city, state_name, city_state, q2.1) 

q3.2 = ggplot() +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = allcities, aes(color= q2.1)) +
  scale_color_gradient("Distance (km)", low='lightpink1', high= 'darkorchid4') +
  geom_sf(data = stateborders, col= "royalblue1", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  ggrepel::geom_label_repel(data= cities3.2, 
                            aes(label= city_state, geometry= geometry), 
                            stat= "sf_coordinates", size= 2) +
  labs(title= "City Distance from the US Border", x= 'longitude', y='latitude')

q3.2
# 3.3 City Distance from Nearest State
cities3.3 <- allcities %>% 
  slice_max(q2.2, n=5) %>% 
  select(city, state_name, city_state, q2.2) 

q3.3 = ggplot() +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = allcities, aes(color= q2.2)) +
  scale_color_gradient("Distance (km)", low='lightpink1', high= 'darkorchid4') +
  geom_sf(data = stateborders, col= "royalblue1", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  ggrepel::geom_label_repel(data= cities3.3, 
                            aes(label= city_state, geometry= geometry), 
                            stat= "sf_coordinates", size= 2) +
  labs(title= "City Distance from the Nearest State Border", x= 'longitude', y='latitude')

q3.3

# 3.4 Equidistance boundary from Mexico and Canada
cities3.4 <- allcities %>% 
  select(city, state_name, city_state, q2.3, q2.4, population) %>% 
  mutate(equidistance= abs(q2.3-q2.4))

equidistant5pop= cities3.4 %>% filter(equidistance<100) %>% slice_max(population, n=5)

q3.4 = ggplot() +
  geom_sf(data = Mexico, fill= "seagreen4") +
  geom_sf(data = Canada, fill= "tomato3") +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = cities3.4, aes(color= equidistance)) +
  scale_color_gradient("Distance (km)", low='white', high= 'blue3') +
  gghighlight(equidistance <100) +
  geom_sf(data = stateborders, col= "grey30", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  ggrepel::geom_label_repel(data= equidistant5pop, 
                            aes(label= city_state, geometry= geometry), 
                            stat= "sf_coordinates", size= 2) +
  labs(title= "Equidistance Boundary from Mexico and Canada", subtitle= "Including the zone's 5 most populous cities",
       x= 'longitude', y='latitude')
q3.4
```
# Question 4
```{r, warning=FALSE, message=FALSE}
# 4.1 Quantifying the Border Zone
q4.1= allcities %>% filter(q2.1<160)

q4.1<- allcities %>% mutate(totalpop= sum(population)) %>% filter(q2.1<160) %>% 
  mutate(pop160km= sum(population)) %>% 
  mutate(percentzonalpop=pop160km/totalpop*100) %>% 
  mutate(count(q4.1)) %>% st_set_geometry(NULL) %>% 
  select(!c(county_fips, county_name, source, id, q2.3, q2.4))

table4.1 <- q4.1 %>% 
  select(n, totalpop, pop160km, percentzonalpop) %>% 
  slice(n=1)

t4.1= knitr::kable(table4.1, caption= "Quantifing the 100-mile Border Zone", col.names= c("Cities in zone", "Total US population", "Population living in zone", "Percentage living in zone")) %>%
   kable_styling("striped", full_width = TRUE, font_size = 14)
t4.1

#My analysis shows that 65.037% of the population resides in the "100-mile Border Zone", matching the ACLU article's estimate, which states that roughly two thirds of the population in the United States lives within this zone. This percent would be higher if including non-contiguous states.

# 4.2 Mapping Border Zone
top10borderpop= allcities %>% filter(q2.1<160) %>% slice_max(population, n=10) 

q4.2 = ggplot() +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = allcities, aes(color= q2.1)) +
  scale_color_gradient("Distance (km)", low='orange', high= 'darkred') +
  gghighlight(q2.1<160) +
  geom_sf(data = stateborders, col= "grey30", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  ggrepel::geom_label_repel(data= top10borderpop, 
                            aes(label= city_state, geometry= geometry), 
                            stat= "sf_coordinates", size= 2, max.overlaps = Inf) +
  labs(title= "Cities Within 100 miles of the US Border", x= 'longitude', y='latitude', subtitle = "Including the 10 most populous cities in the border zone.")

q4.2

# Extra Credit
mostpop_perstate= allcities %>% filter(q2.1<160) %>% group_by(state_name) %>% slice_max(population, n=1)

q4.2b= ggplot() +
  geom_sf(data = CONUS, fill= "lightsteelblue1") +
  geom_sf(data = allcities, aes(color= q2.1)) +
  scale_color_gradient("Distance (km)", low='orange', high= 'darkred') +
  gghighlight(q2.1<160) +
  geom_sf(data = stateborders, col= "grey30", lty= 4) +
  geom_sf(data= USborders, col= "royalblue4") +
  ggrepel::geom_label_repel(data= mostpop_perstate, 
                            aes(label= city_state, geometry= geometry), 
                            stat= "sf_coordinates", size= 1.5, box.padding = .15, 
                            force_pull = 1.2, force = 0.8, max.overlaps = Inf) +
  labs(title= "Cities Within 100 miles of the US Border", x= 'longitude', y='latitude', subtitle = "Including the most populous cities in each state of the border zone.")

q4.2b
```

